<?php

$labels = array();
$labels['foldermaintenance'] = 'Maintenance';
$labels['folders_of'] = 'Les dossiers de';
$labels['folder_name'] = 'Dossier';
$labels['total_messages'] = 'Messages';
$labels['old_messages'] = 'Anciens messages';
$labels['empty'] = 'Vide';
$labels['cleanup'] = 'Nettoyer';
$labels['action'] = 'Lancer le nettoyage';
$labels['none'] = 'Aucun';
$labels['max_days_message'] = 'Nombre de jours maximal de conservation d\'un message :';
$labels['auto_clean'] = 'Nettoyage automatique';
$labels['activated'] = 'Activ&eacute;';

?>
